import { randomUUID } from 'node:crypto';
import type { ActorDocument, AuditEventDocument, BoardDocument, TaskDocument } from './persistence/documents.js';
import { DomainError, type AuditLog, type Task, type TaskView } from './domain.js';
import type { TaskDataRepository, RepositorySession } from './repository.js';
const DEFAULT_BOARD_ID='default'; const MAX_TITLE=140; const MAX_DESCRIPTION=2000; const MAX_COLUMN=80;
export class TaskService {
 constructor(private readonly repository:TaskDataRepository,private readonly now:()=>string=()=>new Date().toISOString()){}
 async list():Promise<TaskView[]>{const tasks=await this.repository.listTasks(DEFAULT_BOARD_ID);const events=await this.repository.listAuditEventsForTasks(tasks.map(t=>t._id));const map=new Map<string,AuditEventDocument[]>();for(const e of events)map.set(e.taskId,[...(map.get(e.taskId)??[]),e]);return tasks.map(t=>this.toView(t,(map.get(t._id)??[]).sort(compareEvents)));}
 async actors():Promise<ActorDocument[]>{return this.repository.listActors();}
 async board(){const b=await this.requireBoard();return {id:b._id,name:b.name,columns:ordered(b).map(({id,name,position})=>({id,name,position}))};}
 async create(titleValue:unknown,descriptionValue:unknown=''):Promise<TaskView>{const title=stringValue(titleValue,'title',MAX_TITLE);const description=optionalString(descriptionValue,'description',MAX_DESCRIPTION);const board=await this.requireBoard();const first=ordered(board)[0];if(!first)throw new DomainError('INVALID_BOARD','board must have at least one column');const time=new Date(this.now());const task:TaskDocument={_id:randomUUID(),boardId:board._id,title,description,statusId:first.id,customValues:{},createdAt:time,updatedAt:time,updatedBy:null};await this.repository.createTask(task);return this.toView(task,[]);}
 async changeStatus(id:string,nextValue:unknown,actorValue:unknown):Promise<{task:TaskView;changed:boolean}>{const next=stringValue(nextValue,'status',80);const actorId=stringValue(actorValue,'actor',80);return this.repository.inTransaction(async session=>{const task=await this.repository.findTask(id,session);const board=await this.requireBoard(session);const actor=await this.repository.findActor(actorId,session);if(!task)throw new DomainError('NOT_FOUND','task not found');if(!actor)throw new DomainError('INVALID_ACTOR','actor must be an active predefined user');const from=board.columns.find(c=>c.id===task.statusId);const to=board.columns.find(c=>c.id===next);if(!from||!to)throw new DomainError('INVALID_STATUS','status must match a board column');if(task.statusId===next)return{task:this.toView(task,await this.repository.listAuditEvents(id,session)),changed:false};const time=new Date(this.now());if(!await this.repository.updateTaskStatus(id,task.statusId,next,time,actor.handle,session))throw new DomainError('CONCURRENT_UPDATE','task changed concurrently; reload and try again');const event=this.event(task,board,actor,from.id,from.name,to.id,to.name,time,'status');await this.repository.appendAuditEvent(event,session);return{task:this.toView({...task,statusId:next,updatedAt:time,updatedBy:actor.handle},await this.repository.listAuditEvents(id,session)),changed:true};});}
 async edit(id:string,titleValue:unknown,descriptionValue:unknown,actorValue:unknown):Promise<TaskView>{const title=stringValue(titleValue,'title',MAX_TITLE);const description=optionalString(descriptionValue,'description',MAX_DESCRIPTION);const actorId=stringValue(actorValue,'actor',80);return this.repository.inTransaction(async session=>{const task=await this.repository.findTask(id,session);const board=await this.requireBoard(session);const actor=await this.repository.findActor(actorId,session);if(!task)throw new DomainError('NOT_FOUND','task not found');if(!actor)throw new DomainError('INVALID_ACTOR','actor must be an active predefined user');if(task.title===title&&task.description===description)return this.toView(task,await this.repository.listAuditEvents(id,session));const column=board.columns.find(c=>c.id===task.statusId);if(!column)throw new DomainError('INVALID_STATUS','task status is not configured');const time=new Date(this.now());await this.repository.updateTaskDetails(id,title,description,time,actor.handle,session);const event=this.event({...task,title},board,actor,column.id,column.name,column.id,column.name,time,'edited','Edited task details');await this.repository.appendAuditEvent(event,session);return this.toView({...task,title,description,updatedAt:time,updatedBy:actor.handle},await this.repository.listAuditEvents(id,session));});}
 async createColumn(nameValue:unknown){const name=stringValue(nameValue,'column name',MAX_COLUMN);return this.repository.inTransaction(async session=>{const b=await this.requireBoard(session);if(b.columns.some(c=>c.name.toLowerCase()===name.toLowerCase()))throw new DomainError('DUPLICATE_COLUMN','column name already exists');b.columns.push({id:randomUUID(),name,position:b.columns.length});b.updatedAt=new Date(this.now());await this.repository.saveBoard(b,session);return this.boardView(b);});}
 async renameColumn(id:string,nameValue:unknown){const name=stringValue(nameValue,'column name',MAX_COLUMN);return this.repository.inTransaction(async session=>{const b=await this.requireBoard(session);const col=b.columns.find(c=>c.id===id);if(!col)throw new DomainError('NOT_FOUND','column not found');if(b.columns.some(c=>c.id!==id&&c.name.toLowerCase()===name.toLowerCase()))throw new DomainError('DUPLICATE_COLUMN','column name already exists');col.name=name;b.updatedAt=new Date(this.now());await this.repository.saveBoard(b,session);return this.boardView(b);});}
 async reorderColumns(idsValue:unknown){if(!Array.isArray(idsValue)||!idsValue.every(x=>typeof x==='string'))throw new DomainError('INVALID_COLUMN_ORDER','columnIds must be a string array');return this.repository.inTransaction(async session=>{const b=await this.requireBoard(session);const known=new Set(b.columns.map(c=>c.id));if(idsValue.length!==known.size||idsValue.some(id=>!known.delete(id)))throw new DomainError('INVALID_COLUMN_ORDER','columnIds must contain every board column exactly once');b.columns=idsValue.map((id,position)=>{const col=b.columns.find(c=>c.id===id)!;return{...col,position};});b.updatedAt=new Date(this.now());await this.repository.saveBoard(b,session);return this.boardView(b);});}
 async deleteColumn(id:string){return this.repository.inTransaction(async session=>{const b=await this.requireBoard(session);if(b.columns.length<=1)throw new DomainError('LAST_COLUMN','board must retain at least one column');if(!b.columns.some(c=>c.id===id))throw new DomainError('NOT_FOUND','column not found');const tasks=await this.repository.listTasks(b._id,session);if(tasks.some(t=>t.statusId===id))throw new DomainError('COLUMN_IN_USE','move tasks out of this column before deleting it');b.columns=b.columns.filter(c=>c.id!==id).sort((a,b)=>a.position-b.position).map((c,position)=>({...c,position}));b.updatedAt=new Date(this.now());await this.repository.saveBoard(b,session);return this.boardView(b);});}
 async logs(id:string):Promise<AuditLog[]>{return(await this.repository.listAuditEvents(id)).sort(compareEvents).map(toAudit);}
 async delete(id:string){if(!await this.repository.deleteTask(id))throw new DomainError('NOT_FOUND','task not found');}
 private event(task:TaskDocument,board:BoardDocument,actor:ActorDocument,fromId:string,fromLabel:string,toId:string,toLabel:string,time:Date,action:'status'|'edited',details?:string):AuditEventDocument{return{_id:randomUUID(),taskId:task._id,boardId:board._id,taskTitle:task.title,actorId:actor._id,actorHandle:actor.handle,action,...(details?{details}:{}),fromStatusId:fromId,fromStatusLabel:fromLabel,toStatusId:toId,toStatusLabel:toLabel,createdAt:time};}
 private async requireBoard(session?:RepositorySession){const board=await this.repository.findBoard(DEFAULT_BOARD_ID,session);if(!board)throw new DomainError('INVALID_BOARD','default board is not configured');return board;}
 private boardView(b:BoardDocument){return{id:b._id,name:b.name,columns:ordered(b).map(({id,name,position})=>({id,name,position}))};}
 private toView(t:TaskDocument,events:AuditEventDocument[]):TaskView{return{id:t._id,title:t.title,description:t.description??'',status:t.statusId,createdAt:t.createdAt.toISOString(),updatedAt:t.updatedAt.toISOString(),updatedBy:t.updatedBy,auditLogs:events.sort(compareEvents).map(toAudit)};}
}
function stringValue(value:unknown,label:string,max:number){if(typeof value!=='string'||!value.trim())throw new DomainError('INVALID_'+label.toUpperCase().replaceAll(' ','_'),label+' is required');const s=value.trim();if(s.length>max)throw new DomainError('INVALID_'+label.toUpperCase().replaceAll(' ','_'),label+' must be '+max+' characters or fewer');return s;}
function optionalString(value:unknown,label:string,max:number){if(value===undefined||value===null)return'';if(typeof value!=='string')throw new DomainError('INVALID_'+label.toUpperCase(),label+' must be a string');if(value.length>max)throw new DomainError('INVALID_'+label.toUpperCase(),label+' must be '+max+' characters or fewer');return value.trim();}
function ordered(b:BoardDocument){return[...b.columns].sort((a,c)=>a.position-c.position||a.id.localeCompare(c.id));}function compareEvents(a:AuditEventDocument,b:AuditEventDocument){return a.createdAt.getTime()-b.createdAt.getTime()||a._id.localeCompare(b._id);}function toAudit(e:AuditEventDocument):AuditLog{return{id:e._id,taskId:e.taskId,taskTitle:e.taskTitle,actor:e.actorHandle,action:e.action,details:e.details,fromStatus:e.fromStatusId,fromStatusLabel:e.fromStatusLabel,toStatus:e.toStatusId,toStatusLabel:e.toStatusLabel,createdAt:e.createdAt.toISOString()};}
